# Test Boxing global installation workflow
# Tests installation directory creation, profile injection, and duplicate prevention

#Requires -Modules Pester
#Requires -Version 7.0

BeforeAll {
    # Create isolated test environment
    $script:TestRoot = Join-Path $env:TEMP "BoxingGlobalInstallTest_$(Get-Random)"
    $script:TestScriptsDir = Join-Path $TestRoot "Scripts"
    $script:TestProfilePath = Join-Path $TestRoot "profile.ps1"

    # Create test directory
    New-Item -Path $TestRoot -ItemType Directory -Force | Out-Null
}

AfterAll {
    # Cleanup
    if (Test-Path $script:TestRoot) {
        Remove-Item -Path $script:TestRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}


Describe "Boxing Global Installation" {
    Context "Scripts directory creation" {
        It "Should create Scripts directory successfully" {
            # Arrange & Act
            if (-not (Test-Path $TestScriptsDir)) {
                New-Item -ItemType Directory -Path $TestScriptsDir -Force | Out-Null
            }

            # Assert
            Test-Path $TestScriptsDir | Should -BeTrue
        }
    }

    Context "Profile creation" {
        It "Should create profile.ps1 when missing" {
            # Arrange - Ensure profile doesn't exist
            if (Test-Path $TestProfilePath) {
                Remove-Item $TestProfilePath -Force
            }

            # Act - Create profile
            $profileDir = Split-Path $TestProfilePath -Parent
            if (-not (Test-Path $profileDir)) {
                New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
            }
            New-Item -ItemType File -Path $TestProfilePath -Force | Out-Null

            # Assert
            Test-Path $TestProfilePath | Should -BeTrue
        }
    }

    Context "Region injection" {
        It "Should inject #region boxing block into profile" {
            # Arrange - Create test profile if needed
            if (-not (Test-Path $TestProfilePath)) {
                $profileDir = Split-Path $TestProfilePath -Parent
                if (-not (Test-Path $profileDir)) {
                    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
                }
                New-Item -ItemType File -Path $TestProfilePath -Force | Out-Null
            }

            # Act - Inject #region block
            $injection = @'

#region boxing
# Auto-generated by Boxing - DO NOT EDIT MANUALLY
$BoxingPath = "$env:USERPROFILE\Documents\PowerShell\Boxing\boxer.ps1"
if (Test-Path $BoxingPath) {
    Set-Alias -Name boxer -Value $BoxingPath -Scope Global
    Set-Alias -Name box -Value $BoxingPath -Scope Global
}
#endregion boxing
'@
            Add-Content -Path $TestProfilePath -Value $injection -Encoding UTF8

            # Assert
            $content = Get-Content $TestProfilePath -Raw
            $content | Should -Match '#region boxing'
            $content | Should -Match '#endregion boxing'
        }
    }

    Context "Duplicate installation prevention" {
        It "Should prevent duplicate #region injection" {
            # Arrange - Profile should already have #region from previous test
            $contentBefore = Get-Content $TestProfilePath -Raw
            $contentBefore | Should -Match '#region boxing'

            # Act - Count occurrences
            $matches = ([regex]'#region boxing').Matches($contentBefore)

            # Assert - Should be exactly one region
            $matches.Count | Should -Be 1
        }
    }
}
