# Test boxer.ps1 auto-installation without touching real installation
# Uses isolated temp environment

#Requires -Modules Pester

BeforeAll {
    # Create isolated test environment
    $script:TestRoot = Join-Path $env:TEMP "BoxingAutoInstallTest_$(Get-Random)"
    $script:FakeUserProfile = $TestRoot
    $script:FakeDocuments = Join-Path $FakeUserProfile "Documents\PowerShell"
    $script:FakeBoxingDir = Join-Path $FakeDocuments "Boxing"
    $script:FakeProfilePath = Join-Path $FakeDocuments "profile.ps1"

    # Backup real environment
    $script:RealUserProfile = $env:USERPROFILE
    $script:RealProfile = $PROFILE.CurrentUserAllHosts

    # Create fake directory structure
    New-Item -Path $FakeDocuments -ItemType Directory -Force | Out-Null

    # Load Install-BoxingSystem function from modules/boxer/init.ps1
    $initScript = Join-Path $PSScriptRoot "..\modules\boxer\init.ps1"
    if (Test-Path $initScript) {
        . $initScript
    }

    # Load boxing.ps1 for core functions
    $boxingScript = Join-Path $PSScriptRoot "..\boxing.ps1"
    if (Test-Path $boxingScript) {
        . $boxingScript
    }
}

AfterAll {
    # Cleanup
    if (Test-Path $script:TestRoot) {
        Remove-Item -Path $script:TestRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe "Boxer Auto-Installation" {
    Context "First-time installation (no existing Boxing directory)" {
        It "Should create Boxing directory structure" {
            # Arrange
            $env:USERPROFILE = $FakeUserProfile
            Test-Path $FakeBoxingDir | Should -BeFalse

            # Act - Simulate what Install-BoxingSystem does
            New-Item -Path $FakeBoxingDir -ItemType Directory -Force | Out-Null
            New-Item -Path "$FakeBoxingDir\Boxes" -ItemType Directory -Force | Out-Null

            # Assert
            Test-Path $FakeBoxingDir | Should -BeTrue
            Test-Path "$FakeBoxingDir\Boxes" | Should -BeTrue

            # Restore
            $env:USERPROFILE = $RealUserProfile
        }

        It "Should copy boxer.ps1 to Boxing directory" {
            # Arrange
            $env:USERPROFILE = $FakeUserProfile
            $distBoxer = Join-Path $PSScriptRoot "..\dist\boxer.ps1"

            if (-not (Test-Path $distBoxer)) {
                Set-TestInconclusive "dist\boxer.ps1 not found - run build-boxer.ps1 first"
            }

            # Act
            Copy-Item -Path $distBoxer -Destination "$FakeBoxingDir\boxer.ps1" -Force

            # Assert
            Test-Path "$FakeBoxingDir\boxer.ps1" | Should -BeTrue
            $content = Get-Content "$FakeBoxingDir\boxer.ps1" -Raw
            $content | Should -Match "Boxing - Common bootstrapper"

            # Restore
            $env:USERPROFILE = $RealUserProfile
        }

        It "Should inject boxing region in profile.ps1" {
            # Arrange
            $env:USERPROFILE = $FakeUserProfile

            # Create fake profile
            $profileContent = @"
# Existing profile content
Write-Host "Profile loaded"
"@
            Set-Content -Path $FakeProfilePath -Value $profileContent

            # Act - Simulate profile injection
            $boxingRegion = @"

#region boxing
# Auto-generated by Boxing - DO NOT EDIT MANUALLY
`$BoxingPath = "`$env:USERPROFILE\Documents\PowerShell\Boxing\boxer.ps1"
if (Test-Path `$BoxingPath) {
    Set-Alias -Name boxer -Value `$BoxingPath -Scope Global
    Set-Alias -Name box -Value `$BoxingPath -Scope Global
}
#endregion boxing
"@
            Add-Content -Path $FakeProfilePath -Value $boxingRegion

            # Assert
            $updatedProfile = Get-Content $FakeProfilePath -Raw
            $updatedProfile | Should -Match "#region boxing"
            $updatedProfile | Should -Match "Set-Alias -Name boxer"
            $updatedProfile | Should -Match "Set-Alias -Name box"

            # Restore
            $env:USERPROFILE = $RealUserProfile
        }
    }

    Context "Duplicate installation prevention" {
        It "Should not inject boxing region twice" {
            # Arrange
            $env:USERPROFILE = $FakeUserProfile

            $profileWithRegion = @"
# Profile content
#region boxing
# Existing boxing region
#endregion boxing
"@
            Set-Content -Path $FakeProfilePath -Value $profileWithRegion

            # Act
            $content = Get-Content $FakeProfilePath -Raw
            $hasRegion = $content -match "#region boxing"

            # Assert - should detect existing region
            $hasRegion | Should -BeTrue

            # Restore
            $env:USERPROFILE = $RealUserProfile
        }
    }

    Context "Version detection during installation" {
        It "Should detect fresh install (no existing version)" {
            # Arrange
            $env:USERPROFILE = $FakeUserProfile

            # Clean Boxing dir if it exists from previous tests
            if (Test-Path $FakeBoxingDir) {
                Remove-Item $FakeBoxingDir -Recurse -Force
            }

            # Act - Fresh install scenario
            $installedVersion = $null

            # Assert
            Test-Path "$FakeBoxingDir\boxer.ps1" | Should -BeFalse
            $installedVersion | Should -BeNullOrEmpty

            # Restore
            $env:USERPROFILE = $RealUserProfile
        }

        It "Should detect upgrade scenario (existing older version)" {
            # Arrange
            $env:USERPROFILE = $FakeUserProfile

            # Create old version
            $oldVersion = @"
# Boxing - Common bootstrapper for boxer and box
# Version: 0.1.50

`$script:BoxerVersion = "0.1.50"
"@
            New-Item -Path $FakeBoxingDir -ItemType Directory -Force | Out-Null
            Set-Content -Path "$FakeBoxingDir\boxer.ps1" -Value $oldVersion

            # Act - Read version
            $content = Get-Content "$FakeBoxingDir\boxer.ps1" -Raw
            $installedVer = if ($content -match 'Version:\s*(\S+)') { $Matches[1] } else { $null }

            # Assert
            $installedVer | Should -Be "0.1.50"
            [version]"0.1.100" -gt [version]$installedVer | Should -BeTrue

            # Restore
            $env:USERPROFILE = $RealUserProfile
        }
    }
}
