# ============================================================================
# Environment Files Generation
# ============================================================================

function Generate-DotEnvFile {
    $envPath = Join-Path $BaseDir ".env"
    $state = Load-State

    $lines = @(
        "# Generated by box - DO NOT EDIT"
        "# Re-run 'box env update' to regenerate"
        "# $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        ""
        "# Project Settings"
    )

    # Project settings from merged config
    # Support: flat (PROJECT_NAME), nested (Project.Name), or direct (Name)
    if ($Config.PROJECT_NAME) {
        $lines += "PROJECT_NAME=$($Config.PROJECT_NAME)"
        $programName = if ($Config.PROGRAM_NAME) { $Config.PROGRAM_NAME } else { $Config.PROJECT_NAME }
        $lines += "PROGRAM_NAME=$programName"
    } elseif ($Config.Name) {
        $lines += "PROJECT_NAME=$($Config.Name)"
        $programName = if ($Config.ProgramName) { $Config.ProgramName } else { $Config.Name }
        $lines += "PROGRAM_NAME=$programName"
    } elseif ($Config.Project -and $Config.Project.Name) {
        $lines += "PROJECT_NAME=$($Config.Project.Name)"
        $lines += "PROGRAM_NAME=$($Config.Project.Name)"
    }

    if ($Config.DESCRIPTION) {
        $lines += "DESCRIPTION=$($Config.DESCRIPTION)"
    } elseif ($Config.Description) {
        $lines += "DESCRIPTION=$($Config.Description)"
    } elseif ($Config.Project -and $Config.Project.Description) {
        $lines += "DESCRIPTION=$($Config.Project.Description)"
    }

    if ($Config.VERSION) {
        $lines += "VERSION=$($Config.VERSION)"
    } elseif ($Config.Version) {
        $lines += "VERSION=$($Config.Version)"
    } elseif ($Config.Project -and $Config.Project.Version) {
        $lines += "VERSION=$($Config.Project.Version)"
    }

    $lines += ""
    $lines += "# Build Configuration"

    # Build settings - use keys as-is (no transformation)
    if ($Config.Build) {
        foreach ($key in $Config.Build.Keys) {
            $value = $Config.Build[$key]
            $lines += "$key=$value"
        }
    }

    $lines += ""
    $lines += "# Package Paths"

    foreach ($pkgName in $state.packages.Keys) {
        $pkg = $state.packages[$pkgName]
        if ($pkg.envs) {
            foreach ($envName in $pkg.envs.Keys) {
                $envValue = $pkg.envs[$envName]
                $lines += "$envName=$envValue"
            }
        }
    }

    # Custom envs from config (Envs section)
    if ($Config.Envs -and $Config.Envs.Count -gt 0) {
        $lines += ""
        $lines += "# Custom Variables"
        foreach ($key in $Config.Envs.Keys) {
            $value = $Config.Envs[$key]
            $lines += "$key=$value"
        }
    }

    $lines -join "`n" | Out-File $envPath -Encoding UTF8 -NoNewline
    Write-Success "Generated .env"
}

function Generate-AllEnvFiles {
    Generate-DotEnvFile
}

# ============================================================================
# Env Commands
# ============================================================================

function Show-EnvList {
    Write-Host ""
    Write-Host "Environment Variables:" -ForegroundColor Cyan
    Write-Host ""

    $state = Load-State

    # Project settings
    Write-Host "  [Project Settings]" -ForegroundColor Yellow
    if ($Config.Project) {
        if ($Config.Project.Name) {
            Write-Host "    PROJECT_NAME = $($Config.Project.Name)" -ForegroundColor White
        }
        if ($Config.Project.Version) {
            Write-Host "    VERSION = $($Config.Project.Version)" -ForegroundColor White
        }
    }

    # Build configuration
    Write-Host ""
    Write-Host "  [Build Configuration]" -ForegroundColor Yellow
    if ($Config.Build) {
        foreach ($key in $Config.Build.Keys) {
            $value = $Config.Build[$key]
            Write-Host "    $key = $value" -ForegroundColor White
        }
    }

    # Package envs
    Write-Host ""
    Write-Host "  [Package Paths]" -ForegroundColor Yellow
    foreach ($pkgName in $state.packages.Keys) {
        $pkg = $state.packages[$pkgName]
        if ($pkg.envs -and $pkg.envs.Count -gt 0) {
            foreach ($envName in $pkg.envs.Keys) {
                $envValue = $pkg.envs[$envName]
                Write-Host "    $envName = $envValue" -ForegroundColor White -NoNewline
                Write-Host " ($pkgName)" -ForegroundColor DarkGray
            }
        }
    }

    # Custom envs from config
    if ($Config.Envs -and $Config.Envs.Count -gt 0) {
        Write-Host ""
        Write-Host "  [Custom Variables]" -ForegroundColor Yellow
        foreach ($key in $Config.Envs.Keys) {
            $value = $Config.Envs[$key]
            Write-Host "    $key = $value" -ForegroundColor White
        }
    }

    Write-Host ""
}
